version: '3.7'

services:

  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=tminas
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links: 
      - database_ignite
    depends_on:
      - database_ignite


volumes:
  pgdata:
    driver: local